version: '3.4'

services:
  bcfinaltheatermanagementbff:
    image: ${DOCKER_REGISTRY-}bcfinaltheatermanagementbff
    build:
      context: .
      dockerfile: src/BcFinalTheaterManagementBff/Dockerfile
    networks:
      - local-shared

  fakemoviecatalogsvc:
    image: ${DOCKER_REGISTRY-}fakemoviecatalogsvc
    build:
      context: .
      dockerfile: src/FakeMovieCatalogSvc/Dockerfile

networks:
  local-shared:
    external:
        name: bc-localdevelopment_network-to-share