version: '3.4'

services:
  bcfinaltheatermanagementbff:
    image: ${DOCKER_REGISTRY-}bcfinaltheatermanagementbff
    build:
      context: .
      dockerfile: src/BcFinalTheaterManagementBff/Dockerfile

  fakemoviecatalogsvc:
    image: ${DOCKER_REGISTRY-}fakemoviecatalogsvc
    build:
      context: .
      dockerfile: src/FakeMovieCatalogSvc/Dockerfile

